sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

language: php

matrix:
  include:
    - php: hhvm-3.9
      sudo: required
      dist: trusty
      group: edge
    - php: nightly
    - php: 7.1
      env: LINT=true
    - php: 7.0
    - php: 5.6
    - php: 5.5
    - php: 5.4
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm

before_install:
  - phpenv config-rm xdebug.ini || true
  - composer self-update

install:
  - composer install

script:
  - if [[ $LINT = true ]]; then
      composer cs-lint;
    fi
  - composer test
