sudo: false

language: php

php:
  - hhvm
  - nightly
  - 7.1
  - 7
  - 5.6
  - 5.5
  - 5.4

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm

before_install:
  - phpenv config-rm xdebug.ini || true
  - composer self-update

install:
  - composer install

script:
  - composer test
