sudo: false

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7
  - nightly

before_install:
  - composer self-update

before_script:
  - phpenv config-rm xdebug.ini

install:
  - composer install

script:
  - composer test
